# Generated by Django 4.0 on 2022-08-07 22:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_category', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_image', models.ImageField(default='logo.svg', max_length=3000, upload_to='products/')),
                ('product_title', models.CharField(max_length=300)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_quantity', models.BigIntegerField(default=0)),
                ('product_brand', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ManyToManyField(to='sneakers.Category')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_image', models.ImageField(max_length=3000, upload_to='products/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sneakers.product')),
            ],
        ),
    ]
