# Generated by Django 4.0 on 2022-08-08 11:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_register_picture'),
        ('sneakers', '0002_rename_productimages_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('quantity', models.BigIntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='unpaid', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sneakers.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.register')),
            ],
        ),
    ]
