# Generated by Django 4.0 on 2022-08-08 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0005_wishlist_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(max_length=3000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
