# Generated by Django 4.0 on 2022-09-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0009_customercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
