# Generated by Django 4.0 on 2022-09-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0011_remove_transaction_address_remove_transaction_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerCart',
        ),
    ]
