# Generated by Django 4.0 on 2022-09-02 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0012_delete_customercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='billing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sneakers.billingaddress'),
        ),
    ]
