# Generated by Django 4.0 on 2022-09-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0014_alter_cart_billing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='billing_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
