# Generated by Django 4.0 on 2022-08-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='picture',
            field=models.ImageField(default='user.png', max_length=3000, upload_to='profiles/'),
        ),
    ]
