# Generated by Django 4.0 on 2022-08-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_register_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
